// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using judocas.Data;

namespace judocas.Migrations
{
    [DbContext(typeof(judocasContext))]
    [Migration("20190908200645_Migration1")]
    partial class Migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("judocas.Models.Faixa", b =>
                {
                    b.Property<long?>("IdFaixa")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_FAIXA")
                        .HasColumnType("BIGINT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnName("DATA_ENTREGA")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("DESCRICAO_FAIXA")
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("IdFiliado")
                        .IsRequired()
                        .HasColumnName("ID_FILIADO")
                        .HasColumnType("BIGINT");

                    b.HasKey("IdFaixa");

                    b.HasIndex("IdFiliado");

                    b.ToTable("Faixa");
                });

            modelBuilder.Entity("judocas.Models.Filiado", b =>
                {
                    b.Property<long?>("IdFiliado")
                        .HasColumnName("ID_FILIADO")
                        .HasColumnType("BIGINT");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnName("CPF")
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnName("DATA_NASC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("EMAIL")
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("IdRG");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("NOME")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnName("OBSERVACOES")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RegistroCbj")
                        .IsRequired()
                        .HasColumnName("REGISTRO_CBJ")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telefone1")
                        .IsRequired()
                        .HasColumnName("TELEFONE_1")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefone2")
                        .IsRequired()
                        .HasColumnName("TELEFONE_2")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdFiliado");

                    b.ToTable("Filiado");
                });

            modelBuilder.Entity("judocas.Models.RG", b =>
                {
                    b.Property<long?>("IdRG")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_RG")
                        .HasColumnType("BIGINT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("IdFiliado")
                        .IsRequired()
                        .HasColumnName("ID_FILIADO")
                        .HasColumnType("BIGINT");

                    b.Property<string>("Numero");

                    b.Property<string>("OrgaoExpedidor");

                    b.HasKey("IdRG");

                    b.ToTable("RG");
                });

            modelBuilder.Entity("judocas.Models.Faixa", b =>
                {
                    b.HasOne("judocas.Models.Filiado", "Filiado")
                        .WithMany("Faixas")
                        .HasForeignKey("IdFiliado")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("judocas.Models.Filiado", b =>
                {
                    b.HasOne("judocas.Models.RG", "RG")
                        .WithOne("Filiado")
                        .HasForeignKey("judocas.Models.Filiado", "IdFiliado")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
