// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using judocas.Data;

namespace judocas.Migrations
{
    [DbContext(typeof(judocasContext))]
    partial class judocasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("judocas.Models.Aluno", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Email");

                    b.Property<long>("FaixaIdFaixa");

                    b.Property<string>("Nome");

                    b.Property<string>("Observacoes");

                    b.Property<string>("RGNumero")
                        .IsRequired();

                    b.Property<string>("RegistroCbj");

                    b.Property<string>("Telefone1");

                    b.Property<string>("Telefone2");

                    b.HasKey("Id");

                    b.HasIndex("FaixaIdFaixa");

                    b.HasIndex("RGNumero");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("judocas.Models.Faixa", b =>
                {
                    b.Property<long>("IdFaixa")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CorFaixa");

                    b.Property<DateTime>("DataEntrega");

                    b.Property<string>("Descricao");

                    b.HasKey("IdFaixa");

                    b.ToTable("Faixa");
                });

            modelBuilder.Entity("judocas.Models.RG", b =>
                {
                    b.Property<string>("Numero")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OrgaoExpedidor");

                    b.HasKey("Numero");

                    b.ToTable("RG");
                });

            modelBuilder.Entity("judocas.Models.Aluno", b =>
                {
                    b.HasOne("judocas.Models.Faixa", "Faixa")
                        .WithMany()
                        .HasForeignKey("FaixaIdFaixa")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("judocas.Models.RG", "RG")
                        .WithMany()
                        .HasForeignKey("RGNumero")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
