// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using judocas.Data;

namespace judocas.Migrations
{
    [DbContext(typeof(judocasContext))]
    partial class judocasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("judocas.Models.Faixa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cor");

                    b.Property<DateTime>("DataEntrega");

                    b.Property<string>("Descricao");

                    b.Property<long>("IdProfessor");

                    b.Property<long?>("ProfessorId");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Faixa");
                });

            modelBuilder.Entity("judocas.Models.Professor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Email");

                    b.Property<string>("Nome")
                        .HasMaxLength(60);

                    b.Property<string>("Observacoes");

                    b.Property<string>("RegistroCbj")
                        .HasMaxLength(20);

                    b.Property<string>("Telefone1")
                        .HasMaxLength(11);

                    b.Property<string>("Telefone2");

                    b.HasKey("Id");

                    b.ToTable("Professor");
                });

            modelBuilder.Entity("judocas.Models.Faixa", b =>
                {
                    b.HasOne("judocas.Models.Professor", "Professor")
                        .WithMany("Faixa")
                        .HasForeignKey("ProfessorId");
                });
#pragma warning restore 612, 618
        }
    }
}
